Homework 2
KiraAndrianova/KiraAndrianova pull request #5
Opened 2022-12-20 13:04 UTC by KiraAndrianova

Selenium locators task, pom.xml changed

2022-12-21 21:59 UTC, Delnote requested changes

2022-12-21 21:59 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/Exercise1Test.java
> +        //Assert that there are 4 items on the header section are displayed
Till this point all the steps should be moved in Base class to avoid code duplicate. It's kind of precondition in your tests.

2022-12-21 21:59 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/Exercise1Test.java
> +        softAssertions.assertThat(webElementListImages.get(3).isDisplayed()).isEqualTo(true);
In this case and all cases below is more convenient to use .isTrue() instead of comparing to 'true'

2022-12-21 21:59 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/Exercise1Test.java
> +                .isEqualTo("Elements packs");
For this list of assertions try to compare with list of strings in one row.

2022-12-21 21:59 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/Exercise1Test.java
> +        driver.quit();
Also move to Base class

2022-12-21 21:59 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex2/Exercise2Test.java
> +            }
All these assertions do not make sense due to going after if statement.

2022-12-24 12:33 UTC, KiraAndrianova commented
Please check the changes

2022-12-26 20:47 UTC, Delnote requested changes

2022-12-26 20:47 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/BaseHW2Test.java
> +    public void loginTest() {
Make it BeforeMethod and don't call in tests

2022-12-26 20:48 UTC, Delnote requested changes

2022-12-26 20:48 UTC, Delnote commented on src/test/java/com/epam/tc/hw2/ex1/Exercise1Test.java
> +        softAssertions.assertThat(webElementListImages.get(3).isDisplayed()).isTrue();
All this validations may be done in one row using foreach()

2023-01-09 10:05 UTC, KiraAndrianova commented
Please check the last changes

2023-01-12 19:56 UTC, Delnote approved these changes

2023-01-13 09:39 UTC, merged