Homework 3
KiraAndrianova/KiraAndrianova pull request #6
Opened 2022-12-25 10:47 UTC by KiraAndrianova

2023-01-01 21:51 UTC, Delnote requested changes
All page objects and other main stuff should be moved from 'test' section to main java section.

2023-01-01 21:51 UTC, Delnote commented on src/test/java/com/epam/tc/hw3/pages/differentelementspage/DifferentElementsPage.java
> +    }
For radioButtons it's better to find button and then click on it. In other way this step may be passed even if radioButton has not been clicked.

2023-01-01 21:51 UTC, Delnote commented on src/test/java/com/epam/tc/hw3/pages/homepage/HomePage.java
> +        return webElementListImages.stream().map(WebElement::isDisplayed).collect(Collectors.toList());
Method name says that waits list of images and not list of booleans. This method should be modified. It doesn't make sense to return list of boolean.

2023-01-01 21:51 UTC, Delnote commented on src/test/java/com/epam/tc/hw3/test/DifferentElementsTest.java
> +        WebDriverWait wait = new WebDriverWait(webDriver, 10);
This should be moved to before

2023-01-01 21:51 UTC, Delnote commented on src/test/java/com/epam/tc/hw3/test/DifferentElementsTest.java
> +        }
Need to get rid of cycles in tests.

2023-01-01 21:51 UTC, Delnote commented on src/test/java/com/epam/tc/hw3/test/HomePageTest.java
> +                .allMatch(t -> t == true)
It should be modified after getListImages changes

2023-01-10 11:25 UTC, KiraAndrianova commented
Please check the updates

2023-01-12 19:57 UTC, Delnote approved these changes

2023-01-13 09:39 UTC, merged